name: Run test1.py daily

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests
        pip install js2py

    - name: Run test1.py
      run: python test1.py

    - name: Commit and push changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add 第二批.txt
        git commit -m "Remove failed login accounts" || true
        git push